/*******************************************************************************
 * Copyright 2017 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_modelinterface is a generated GoMock package.
package mocks

import (
	. "db/modelinterface"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// InsertComposeFile mocks base method
func (m *MockService) InsertComposeFile(description string) (map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "InsertComposeFile", description)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertComposeFile indicates an expected call of InsertComposeFile
func (mr *MockServiceMockRecorder) InsertComposeFile(description interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertComposeFile", reflect.TypeOf((*MockService)(nil).InsertComposeFile), description)
}

// GetAppList mocks base method
func (m *MockService) GetAppList() ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetAppList")
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppList indicates an expected call of GetAppList
func (mr *MockServiceMockRecorder) GetAppList() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppList", reflect.TypeOf((*MockService)(nil).GetAppList))
}

// GetApp mocks base method
func (m *MockService) GetApp(app_id string) (map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "GetApp", app_id)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp
func (mr *MockServiceMockRecorder) GetApp(app_id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockService)(nil).GetApp), app_id)
}

// UpdateAppInfo mocks base method
func (m *MockService) UpdateAppInfo(app_id, description string) error {
	ret := m.ctrl.Call(m, "UpdateAppInfo", app_id, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppInfo indicates an expected call of UpdateAppInfo
func (mr *MockServiceMockRecorder) UpdateAppInfo(app_id, description interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppInfo", reflect.TypeOf((*MockService)(nil).UpdateAppInfo), app_id, description)
}

// DeleteApp mocks base method
func (m *MockService) DeleteApp(app_id string) error {
	ret := m.ctrl.Call(m, "DeleteApp", app_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApp indicates an expected call of DeleteApp
func (mr *MockServiceMockRecorder) DeleteApp(app_id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApp", reflect.TypeOf((*MockService)(nil).DeleteApp), app_id)
}

// GetAppState mocks base method
func (m *MockService) GetAppState(app_id string) (string, error) {
	ret := m.ctrl.Call(m, "GetAppState", app_id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppState indicates an expected call of GetAppState
func (mr *MockServiceMockRecorder) GetAppState(app_id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppState", reflect.TypeOf((*MockService)(nil).GetAppState), app_id)
}

// UpdateAppState mocks base method
func (m *MockService) UpdateAppState(app_id, state string) error {
	ret := m.ctrl.Call(m, "UpdateAppState", app_id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppState indicates an expected call of UpdateAppState
func (mr *MockServiceMockRecorder) UpdateAppState(app_id, state interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppState", reflect.TypeOf((*MockService)(nil).UpdateAppState), app_id, state)
}

