/*******************************************************************************
 * Copyright 2018 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/
// Code generated by MockGen. DO NOT EDIT.
// Source: src/controller/notification/apps/apps.go

// Package mock_apps is a generated GoMock package.
package mock_apps

import (
	dockercontroller "controller/dockercontroller"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// SubscribeEvent mocks base method
func (m *MockCommand) SubscribeEvent(body string) (map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "SubscribeEvent", body)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEvent indicates an expected call of SubscribeEvent
func (mr *MockCommandMockRecorder) SubscribeEvent(body interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvent", reflect.TypeOf((*MockCommand)(nil).SubscribeEvent), body)
}

// SendNotification mocks base method
func (m *MockCommand) SendNotification(event dockercontroller.Event) {
	m.ctrl.Call(m, "SendNotification", event)
}

// SendNotification indicates an expected call of SendNotification
func (mr *MockCommandMockRecorder) SendNotification(event interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockCommand)(nil).SendNotification), event)
}

// UnsubscribeEvent mocks base method
func (m *MockCommand) UnsubscribeEvent(body string) error {
	ret := m.ctrl.Call(m, "UnsubscribeEvent", body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeEvent indicates an expected call of UnsubscribeEvent
func (mr *MockCommandMockRecorder) UnsubscribeEvent(body interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeEvent", reflect.TypeOf((*MockCommand)(nil).UnsubscribeEvent), body)
}
