// Code generated by MockGen. DO NOT EDIT.
// Source: src/controller/monitoring/apps/apps.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// EnableEventMonitoring mocks base method
func (m *MockCommand) EnableEventMonitoring(appId, path string) error {
	ret := m.ctrl.Call(m, "EnableEventMonitoring", appId, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableEventMonitoring indicates an expected call of EnableEventMonitoring
func (mr *MockCommandMockRecorder) EnableEventMonitoring(appId, path interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableEventMonitoring", reflect.TypeOf((*MockCommand)(nil).EnableEventMonitoring), appId, path)
}

// DisableEventMonitoring mocks base method
func (m *MockCommand) DisableEventMonitoring(appId, path string) error {
	ret := m.ctrl.Call(m, "DisableEventMonitoring", appId, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableEventMonitoring indicates an expected call of DisableEventMonitoring
func (mr *MockCommandMockRecorder) DisableEventMonitoring(appId, path interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableEventMonitoring", reflect.TypeOf((*MockCommand)(nil).DisableEventMonitoring), appId, path)
}
